variables:
  IMAGE: $REPO_URL:$CI_COMMIT_SHA
  IMAGE_STAGING: $REPO_URL_STAGING:$CI_COMMIT_SHA

stages:
  - build
  - deploy

build_production:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - apk add --no-cache curl py-pip jq
    - pip install awscli
  script:
    - eval $(aws ecr get-login --no-include-email)
    - docker build -t $REPO_URL:$CI_COMMIT_SHA -t $REPO_URL:latest .
    - docker push $REPO_URL:$CI_COMMIT_SHA
    - docker push $REPO_URL:latest
  only:
    - master
  tags:
    - docker

build_staging:
  image: docker:latest
  services:
    - docker:dind
  stage: build
  before_script:
    - apk add --no-cache curl py-pip jq
    - pip install awscli
  script:
    - eval $(aws ecr get-login --no-include-email)
    - docker build -t $REPO_URL_STAGING:$CI_COMMIT_SHA -t $REPO_URL_STAGING:latest .
    - docker push $REPO_URL_STAGING:$CI_COMMIT_SHA
    - docker push $REPO_URL_STAGING:latest
  only:
    - dev
  tags:
    - docker

deploy_production:
  image: python:latest
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install zip
    - pip install awscli
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - sed -i 's|IMAGE|'"$IMAGE"'|g' ./deployment/production/Dockerrun.aws.json
    - mkdir aws
    - cp -r ./deployment/production/* aws
    - cd aws
    - zip -vr aws-hunty-backend-$CI_COMMIT_SHA ./
    - aws s3 cp aws-hunty-backend-$CI_COMMIT_SHA.zip s3://elasticbeanstalk-$AWS_DEFAULT_REGION-$AWS_ACCOUNT_ID/aws-hunty-backend-$CI_COMMIT_SHA.zip
    - aws elasticbeanstalk create-application-version --application-name $EB_APP_NAME --version-label aws-hunty-backend-$CI_COMMIT_SHA --region $AWS_DEFAULT_REGION --source-bundle S3Bucket=elasticbeanstalk-$AWS_DEFAULT_REGION-$AWS_ACCOUNT_ID,S3Key=aws-hunty-backend-$CI_COMMIT_SHA.zip
    - aws elasticbeanstalk update-environment --application-name $EB_APP_NAME --environment-name $EB_ENV_NAME --region $AWS_DEFAULT_REGION --version-label aws-hunty-backend-$CI_COMMIT_SHA
  only:
    - master

deploy_staging:
  image: python:latest
  stage: deploy
  before_script:
    - apt-get update
    - apt-get install zip
    - pip install awscli
  script:
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set region $AWS_DEFAULT_REGION
    - sed -i 's|IMAGE|'"$IMAGE_STAGING"'|g' ./deployment/staging/Dockerrun.aws.json
    - mkdir aws
    - cp -r ./deployment/staging/* aws
    - cd aws
    - zip -vr aws-hunty-backend-stg-$CI_COMMIT_SHA ./
    - aws s3 cp aws-hunty-backend-stg-$CI_COMMIT_SHA.zip s3://elasticbeanstalk-$AWS_DEFAULT_REGION-$AWS_ACCOUNT_ID/aws-hunty-backend-stg-$CI_COMMIT_SHA.zip
    - aws elasticbeanstalk create-application-version --application-name $EB_APP_NAME_STAGING --version-label aws-hunty-backend-stg-$CI_COMMIT_SHA --region $AWS_DEFAULT_REGION --source-bundle S3Bucket=elasticbeanstalk-$AWS_DEFAULT_REGION-$AWS_ACCOUNT_ID,S3Key=aws-hunty-backend-stg-$CI_COMMIT_SHA.zip
    - aws elasticbeanstalk update-environment --application-name $EB_APP_NAME_STAGING --environment-name $EB_ENV_NAME_STAGING --region $AWS_DEFAULT_REGION --version-label aws-hunty-backend-stg-$CI_COMMIT_SHA
  only:
    - dev
